#include "codegen.h"
#include "parser.h"
#include "symbol_table.h"
#include "globals.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static inline void add_pending_function(struct codegen_t *codegen, struct parser_node *function, char *current_processing_function_name){
    if(!codegen->pending_functions) codegen->pending_functions = calloc(codegen->pending_function_capacity, sizeof(struct pending_function_t));
    if(codegen->pending_function_count >= codegen->pending_function_capacity) {
        codegen->pending_function_capacity *= 2;
        struct pending_function_t *tmp = realloc(codegen->pending_functions, sizeof(struct pending_function_t) * codegen->pending_function_capacity);
        if(!tmp) {LOG_M_ERR("add_pending_function - \"struct pending_function_t *tmp\" is null"); return;}

        codegen->pending_functions = tmp;
    }
    codegen->pending_functions[codegen->pending_function_count].func_node = function;
    codegen->pending_functions[codegen->pending_function_count].mangled_name = function->data.function.mangled_name;
    

    codegen->pending_function_count++;
}

static inline char *generate_mangled_function_name(struct codegen_t *codegen, char *original_name, int scope_id) {
    if (codegen->function_depth > 0 && codegen->current_processing_function_name) {
        int required_len = snprintf(NULL, 0, "%s_%s_S_%d", codegen->current_processing_function_name, original_name, scope_id);

        char *mangled_name = malloc(required_len + 1);

        if (mangled_name) {
            sprintf(mangled_name, "%s_%s_S_%d", codegen->current_processing_function_name, original_name, scope_id);
            return mangled_name;
        }
    }

    return strdup(original_name);
}

static inline char *generate_mangled_loop_name(struct codegen_t *codegen, int loop_id) {
    int required_len = snprintf(NULL, 0, "LOOP_S_%d", loop_id);

    char *mangled_name = malloc(required_len + 1);

    if (mangled_name) {
        sprintf(mangled_name, "LOOP_S_%d", loop_id);
        return mangled_name;
    }

    return NULL;
}

static inline char *generate_mangled_loop_control_name(struct codegen_t *codegen, int loop_control_id) {
    int required_len = snprintf(NULL, 0, "LOOP_CONTROL_S_%d", loop_control_id);

    char *mangled_name = malloc(required_len + 1);

    if (mangled_name) {
        sprintf(mangled_name, "LOOP_CONTROL_S_%d", loop_control_id);
        return mangled_name;
    }

    return NULL;
}

struct codegen_t *codegen_create_codegen(struct parser_t *restrict parser, const char *restrict out_filename) {
    struct codegen_t *cg = calloc(1, sizeof(struct codegen_t));
    if (!cg) {
        fprintf(stderr, "{ERR} Codegen memory allocation failed\n");
        return NULL;
    }

    cg->output_file = fopen(out_filename, "w");
    if (!cg->output_file) {
        fprintf(stderr, "{ERR} Could not open output file: %s\n", out_filename);
        free(cg);
        return NULL;
    }

    cg->parser = parser;
    cg->current_scope = parser->current_scope;
    cg->type_table = parser->type_table;
    cg->pending_function_capacity = 4;

    fprintf(cg->output_file, "; --- Generated by Hupeyaszih Compiler ---\n");
    fprintf(cg->output_file, "section .text\n");
    fprintf(cg->output_file, "    global _start\n\n");

    return cg;
}

void codegen_generate(struct codegen_t *restrict codegen, struct parser_t *restrict parser, struct symbol_table *global_scope){
    codegen->current_scope = global_scope;
    codegen_calculate_offsets(global_scope, 0);

    fprintf(codegen->output_file, "_start:\n");

    fprintf(codegen->output_file, "    call main\n\n");
    fprintf(codegen->output_file, "    mov rdi, rax\n");
    fprintf(codegen->output_file, "    mov rax, 60\n");
    fprintf(codegen->output_file, "    syscall\n");
    for(int i = 0; i < parser->node_count; ++i){
        codegen_pre_codegen_analysis(parser->nodes[i], codegen->current_scope);
    }
    for(int i = 0; i < parser->node_count; ++i){
        codegen_visit_node(codegen, parser->nodes[i], global_scope, 0);
    }
    codegen_flush_pending_functions(codegen, global_scope);

    C_LOG_OK("Codegen finished successfully");
}

void codegen_pre_codegen_analysis(struct parser_node *node, struct symbol_table *current_scope) {
    if (!node) return;
    if(node->left_node) codegen_pre_codegen_analysis(node->left_node, current_scope);
    if(node->right_node) codegen_pre_codegen_analysis(node->right_node, current_scope);

    switch (node->type) {
        case PARSER_NODE_BLOCK: {
            int base = 0;
            if (current_scope) {

                base = current_scope->current_total_offset;
            }
            codegen_calculate_offsets(node->data.block.scope, base);

            for (int i = 0; i < node->data.block.count; i++) {
                struct parser_node *stmt = node->data.block.statements[i];
                if (stmt->type == PARSER_NODE_BLOCK || stmt->type == PARSER_NODE_FUNCTION) {
                    codegen_pre_codegen_analysis(stmt, node->data.block.scope);
                }
            }
            break;
        }
        case PARSER_NODE_FUNCTION: {
            if(NULL == node->data.function.return_type) return;
            codegen_pre_codegen_analysis(node->data.function.body, node->data.function.body->data.block.scope);
            break;
        }
        case PARSER_NODE_LOOP: {
            if(NULL == node->data.loop.body) return;
            codegen_pre_codegen_analysis(node->data.loop.body, node->data.loop.body->data.block.scope);
            break;
        }case PARSER_NODE_BREAK: {
            if(NULL == node->data.loop_control.condition) return;
            codegen_pre_codegen_analysis(node->data.loop_control.condition, node->data.loop_control.condition->data.block.scope);
            if(NULL == node->data.loop_control.body) return;
            codegen_pre_codegen_analysis(node->data.loop_control.body, node->data.loop_control.body->data.block.scope);
            break;
        }case PARSER_NODE_CONTINUE: {
            if(NULL == node->data.loop_control.condition) return;
            codegen_pre_codegen_analysis(node->data.loop_control.condition, node->data.loop_control.condition->data.block.scope);
            if(NULL == node->data.loop_control.body) return;
            codegen_pre_codegen_analysis(node->data.loop_control.body, node->data.loop_control.body->data.block.scope);
            break;
        }case PARSER_NODE_CALL:{
            struct symbol_t *sym = symbol_table_look_up(current_scope, node->data.call.name);
            if(NULL == sym){
                C_LOG_ERR("function \"%s\" is not defined, line %d", node->data.call.name, node->line);
                break;
            }
            node->type_info = sym->type; 
        }
        default: break;
    }
}

void codegen_visit_node(struct codegen_t *restrict codegen, struct parser_node *restrict node, struct symbol_table *global_scope, int flush_mode) {
    if (!node) return;

    switch (node->type) {
        case PARSER_NODE_NUMBER:
            if(node->left_node) codegen_visit_node(codegen, node->left_node, global_scope, 0);
            if(node->right_node) codegen_visit_node(codegen, node->right_node, global_scope, 0);
            fprintf(codegen->output_file, "    mov rax, %s\n", node->data.literal_data);
            break;
        case PARSER_NODE_FUNCTION:{
            if(NULL == node->data.function.return_type) return;
            char *new_mangled_name = node->data.function.name;
            if(flush_mode == 0){
                new_mangled_name = generate_mangled_function_name(codegen, node->data.function.name, codegen->current_scope->scope_id);
                free(node->data.function.mangled_name);
                node->data.function.mangled_name = new_mangled_name;
                struct symbol_t *func_sym = symbol_table_look_up(codegen->current_scope, node->data.function.name);

                if (func_sym) {
                    free(func_sym->mangled_name);
                    func_sym->mangled_name = strdup(new_mangled_name); 
                }
            }
            if (codegen->function_depth > 0) {add_pending_function(codegen, node, new_mangled_name); break;}
            
            codegen->function_depth++;
            char *old_processing_name = codegen->current_processing_function_name;
            codegen->current_processing_function_name = node->data.function.mangled_name;

            fprintf(codegen->output_file, "%s:\n", node->data.function.mangled_name);

            fprintf(codegen->output_file, "    push rbp\n");
            fprintf(codegen->output_file, "    mov rbp, rsp\n");

            int stack_size = node->data.function.body->data.block.scope->total_stack_size;
            if (stack_size > 0) {
                fprintf(codegen->output_file, "    sub rsp, %d\n", stack_size);
            }

            const char *arg_regs[] = {"rdi", "rsi", "rdx", "rcx", "r8", "r9"};
            for (int i = 0; i < node->data.function.param_count; i++) {
                char *param_name = node->data.function.params->data.block.statements[i]->data.variable_name;
                struct symbol_t *sym = symbol_table_look_up(node->data.function.body->data.block.scope, param_name);

                if (sym) {
                    fprintf(codegen->output_file, "    mov [rbp-%d], %s\n", sym->stack_offset, arg_regs[i]);
                }
            }

            struct symbol_table *old_scope = codegen->current_scope;
            codegen->current_scope = node->data.function.body->data.block.scope;
            codegen_visit_node(codegen, node->data.function.body, global_scope, 0);

            fprintf(codegen->output_file, "    leave\n");
            fprintf(codegen->output_file, "    ret\n");
            codegen_flush_pending_functions(codegen, global_scope);

            codegen->current_scope = old_scope;
            codegen->current_processing_function_name = old_processing_name; 
            codegen->function_depth--;
    break;
    }
        case PARSER_NODE_BLOCK: {
            struct symbol_table *previous = codegen->current_scope;
            codegen->current_scope = node->data.block.scope;

            for(int i = 0; i < node->data.block.count; ++i){
                codegen_visit_node(codegen, node->data.block.statements[i], global_scope, 0);
            }
            codegen->current_scope = previous;
            break;
        }
        case PARSER_NODE_CALL: {
            if(NULL == node->type_info) return;
            const char *arg_regs[] = {"rdi", "rsi", "rdx", "rcx", "r8", "r9"};
            int arg_count = node->data.call.arg_count;

            for (int i = 0; i < arg_count; i++) {
                codegen_visit_node(codegen, node->data.call.args[i], global_scope, 0);
                fprintf(codegen->output_file, "    push rax\n");
            }

            for (int i = arg_count - 1; i >= 0; i--) {
                fprintf(codegen->output_file, "    pop %s\n", arg_regs[i]);
            }

            struct symbol_t *sym = symbol_table_look_up(codegen->current_scope, node->data.call.name);
            if(NULL == sym){
                C_LOG_ERR("function \"%s\" is not defined, line %d", node->data.call.name, node->line);
                break;
            }

            if (sym->mangled_name) {
                fprintf(codegen->output_file, "    call %s\n", sym->mangled_name);
            } else {
                fprintf(codegen->output_file, "    call %s\n", node->data.call.name);
            }
            break;
        }case PARSER_NODE_LOOP: {
            if(NULL == node->data.loop.body) return;
            node->data.loop.mangled_name = generate_mangled_loop_name(codegen, node->data.loop.loop_id);
            fprintf(codegen->output_file, "%s_START:\n", node->data.loop.mangled_name);
            codegen_visit_node(codegen, node->data.loop.body, global_scope, 0);
            fprintf(codegen->output_file, "    jmp %s_START\n", node->data.loop.mangled_name);
            fprintf(codegen->output_file, "%s_END:\n", node->data.loop.mangled_name);
            break;
        }case PARSER_NODE_BREAK:{
            if(NULL == node->data.loop_control.body || NULL == node->data.loop_control.condition) return;
            node->data.loop_control.mangled_loop_name = generate_mangled_loop_name(codegen, node->data.loop_control.loop_id);
            node->data.loop_control.mangled_loop_control_name = generate_mangled_loop_control_name(codegen, node->data.loop_control.loop_control_id);
            
            codegen_visit_node(codegen, node->data.loop_control.condition, global_scope, 0);
            fprintf(codegen->output_file, "    test rax, rax\n");
            fprintf(codegen->output_file, "    jz %s_BREAK_SKIP\n", node->data.loop_control.mangled_loop_control_name);

            fprintf(codegen->output_file, "%s_BREAK_START:\n", node->data.loop_control.mangled_loop_control_name);
            codegen_visit_node(codegen, node->data.loop_control.body, global_scope, 0);
            fprintf(codegen->output_file, "    jmp %s_END\n", node->data.loop_control.mangled_loop_name);
            fprintf(codegen->output_file, "%s_BREAK_SKIP:\n", node->data.loop_control.mangled_loop_control_name);
            break;
        }case PARSER_NODE_CONTINUE:{
            if(NULL == node->data.loop_control.body || NULL == node->data.loop_control.condition) return;
            node->data.loop_control.mangled_loop_name = generate_mangled_loop_name(codegen, node->data.loop_control.loop_id);
            node->data.loop_control.mangled_loop_control_name = generate_mangled_loop_control_name(codegen, node->data.loop_control.loop_control_id);
            
            codegen_visit_node(codegen, node->data.loop_control.condition, global_scope, 0);
            fprintf(codegen->output_file, "    test rax, rax\n");
            fprintf(codegen->output_file, "    jz %s_CONTINUE_SKIP\n", node->data.loop_control.mangled_loop_control_name);

            fprintf(codegen->output_file, "%s_CONTINUE_START:\n", node->data.loop_control.mangled_loop_control_name);
            codegen_visit_node(codegen, node->data.loop_control.body, global_scope, 0);
            fprintf(codegen->output_file, "    jmp %s_START\n", node->data.loop_control.mangled_loop_name);
            fprintf(codegen->output_file, "%s_CONTINUE_SKIP:\n", node->data.loop_control.mangled_loop_control_name);
            break;
        }case PARSER_NODE_VARIABLE_DECLARATION:{
            if(node->right_node) codegen_visit_node(codegen, node->right_node, global_scope, 0);
            struct symbol_t *symbol = symbol_table_look_up(codegen->current_scope, node->data.variable_name);
            if(NULL == symbol) {C_LOG_ERR("variable \"%s\" is not defined, line: %d", node->data.variable_name, node->line); break;}
            fprintf(codegen->output_file, "    mov [rbp-%d], rax\n", symbol->stack_offset);
            break;
        }case PARSER_NODE_VARIABLE_ASSIGMENT:{
            if(NULL == node->data.variable_name) return;
            if(node->right_node) codegen_visit_node(codegen, node->right_node, global_scope, 0);
            struct symbol_t *symbol = symbol_table_look_up(codegen->current_scope, node->data.variable_name);
            if(NULL == symbol) {C_LOG_ERR("variable \"%s\" is not defined, line: %d", node->data.variable_name, node->line); break;}
            fprintf(codegen->output_file, "    mov [rbp-%d], rax\n", symbol->stack_offset);
            break;
        }
        case PARSER_NODE_IDENTIFIER:{
            struct symbol_t *symbol = symbol_table_look_up(codegen->current_scope, node->data.variable_name);
            if(NULL == symbol) {C_LOG_ERR("variable \"%s\" is not defined, line: %d", node->data.variable_name, node->line); break;}
            fprintf(codegen->output_file, "    mov rax, [rbp-%d]\n", symbol->stack_offset);
            break;
        }
        case PARSER_NODE_UNARY_MINUS:
            if(node->right_node) codegen_visit_node(codegen, node->right_node, global_scope, 0);
            fprintf(codegen->output_file, "    neg rax\n");
            break;
        case PARSER_NODE_UNARY_BANG:
            if(node->right_node) codegen_visit_node(codegen, node->right_node, global_scope, 0);
            fprintf(codegen->output_file, "    test rax, rax\n");
            fprintf(codegen->output_file, "    sete al\n");
            fprintf(codegen->output_file, "    movzx rax, al\n");
            break;
        case PARSER_NODE_BANG_EQUAL: 
            if(node->left_node) codegen_visit_node(codegen, node->left_node, global_scope, 0);
            fprintf(codegen->output_file, "    push rax \n");
            if(node->right_node) codegen_visit_node(codegen, node->right_node, global_scope, 0);
            fprintf(codegen->output_file, "    pop rcx \n");
            fprintf(codegen->output_file, "    cmp rcx, rax \n");
            fprintf(codegen->output_file, "    setne al \n");
            fprintf(codegen->output_file, "    movzx rax, al \n");
            break;
        case PARSER_NODE_EQUAL_EQUAL: 
            if(node->left_node) codegen_visit_node(codegen, node->left_node, global_scope, 0);
            fprintf(codegen->output_file, "    push rax \n");
            if(node->right_node) codegen_visit_node(codegen, node->right_node, global_scope, 0);
            fprintf(codegen->output_file, "    pop rcx \n");
            fprintf(codegen->output_file, "    cmp rcx, rax \n");
            fprintf(codegen->output_file, "    sete al \n");
            fprintf(codegen->output_file, "    movzx rax, al \n");
            break;
        case PARSER_NODE_LESS: 
            if(node->left_node) codegen_visit_node(codegen, node->left_node, global_scope, 0);
            fprintf(codegen->output_file, "    push rax \n");
            if(node->right_node) codegen_visit_node(codegen, node->right_node, global_scope, 0);
            fprintf(codegen->output_file, "    pop rcx \n");
            fprintf(codegen->output_file, "    cmp rcx, rax \n");
            fprintf(codegen->output_file, "    setl al \n");
            fprintf(codegen->output_file, "    movzx rax, al \n");
            break;
        case PARSER_NODE_GREATER: 
            if(node->left_node) codegen_visit_node(codegen, node->left_node, global_scope, 0);
            fprintf(codegen->output_file, "    push rax \n");
            if(node->right_node) codegen_visit_node(codegen, node->right_node, global_scope, 0);
            fprintf(codegen->output_file, "    pop rcx \n");
            fprintf(codegen->output_file, "    cmp rcx, rax \n");
            fprintf(codegen->output_file, "    setg al \n");
            fprintf(codegen->output_file, "    movzx rax, al \n");
            break;
        case PARSER_NODE_LESS_EQUAL: 
            if(node->left_node) codegen_visit_node(codegen, node->left_node, global_scope, 0);
            fprintf(codegen->output_file, "    push rax \n");
            if(node->right_node) codegen_visit_node(codegen, node->right_node, global_scope, 0);
            fprintf(codegen->output_file, "    pop rcx \n");
            fprintf(codegen->output_file, "    cmp rcx, rax \n");
            fprintf(codegen->output_file, "    setle al \n");
            fprintf(codegen->output_file, "    movzx rax, al \n");
            break;
        case PARSER_NODE_GREATER_EQUAL: 
            if(node->left_node) codegen_visit_node(codegen, node->left_node, global_scope, 0);
            fprintf(codegen->output_file, "    push rax \n");
            if(node->right_node) codegen_visit_node(codegen, node->right_node, global_scope, 0);
            fprintf(codegen->output_file, "    pop rcx \n");
            fprintf(codegen->output_file, "    cmp rcx, rax \n");
            fprintf(codegen->output_file, "    setge al \n");
            fprintf(codegen->output_file, "    movzx rax, al \n");
            break;
        case PARSER_NODE_PLUS: 
            if(node->left_node) codegen_visit_node(codegen, node->left_node, global_scope, 0);
            fprintf(codegen->output_file, "    push rax \n");
            if(node->right_node) codegen_visit_node(codegen, node->right_node, global_scope, 0);
            fprintf(codegen->output_file, "    pop rcx \n");
            fprintf(codegen->output_file, "    add rax, rcx \n");
            break;
        case PARSER_NODE_MINUS: 
            if(node->left_node) codegen_visit_node(codegen, node->left_node, global_scope, 0);
            fprintf(codegen->output_file, "    push rax \n");
            if(node->right_node) codegen_visit_node(codegen, node->right_node, global_scope, 0);
            fprintf(codegen->output_file, "    pop rcx \n");
            fprintf(codegen->output_file, "    sub rcx, rax \n");
            fprintf(codegen->output_file, "    mov rax, rcx \n");
            break;
        case PARSER_NODE_MUL: 
            if(node->left_node) codegen_visit_node(codegen, node->left_node, global_scope, 0);
            fprintf(codegen->output_file, "    push rax \n");
            if(node->right_node) codegen_visit_node(codegen, node->right_node, global_scope, 0);
            fprintf(codegen->output_file, "    pop rcx \n");
            fprintf(codegen->output_file, "    imul rcx, rax \n");
            fprintf(codegen->output_file, "    mov rax, rcx \n");
            break;
        case PARSER_NODE_DIVIDE: 
            if(node->left_node) codegen_visit_node(codegen, node->left_node, global_scope, 0);
            fprintf(codegen->output_file, "    push rax \n");
            if(node->right_node) codegen_visit_node(codegen, node->right_node, global_scope, 0);
            fprintf(codegen->output_file, "    mov rcx, rax\n");
            fprintf(codegen->output_file, "    pop rax\n");
            fprintf(codegen->output_file, "    cqo\n");
            fprintf(codegen->output_file, "    idiv rcx \n");
            break;
    }
}

void codegen_flush_pending_functions(struct codegen_t* codegen, struct symbol_table *global_scope) {
    int count_to_process = codegen->pending_function_count;
    
    codegen->pending_function_count = 0; 

    for (int i = 0; i < count_to_process; i++) {
        codegen->function_depth = 0; 
        
        codegen_visit_node(codegen, codegen->pending_functions[i].func_node, global_scope, 1);
    }

    if (codegen->pending_function_count > 0) {
        codegen_flush_pending_functions(codegen, global_scope);
    }
}

void codegen_calculate_offsets(struct symbol_table *scope, int base_offset) {
    if (!scope) return;

    int current_offset = base_offset;

    for (int i = 0; i < scope->symbol_count; i++) {
        struct symbol_t *sym = &scope->symbols[i];
        if (sym->kind == SYMBOL_KIND_VARIABLE) {
            int size_padding = (sym->type->size + 7) & ~7;
            current_offset += size_padding;
            sym->stack_offset = current_offset; 
        }
    }
    
    scope->current_total_offset = current_offset;
    
    scope->total_stack_size = (current_offset + 15) & ~15;
    if (scope->parent && scope->total_stack_size > scope->parent->total_stack_size) {
        scope->parent->total_stack_size = scope->total_stack_size;
    }
}

void codegen_delete_codegen(struct codegen_t *restrict cg) {
    if (!cg) return;

    if (cg->pending_functions) {
        for (int i = 0; i < cg->pending_function_count; i++) {
            free(cg->pending_functions[i].mangled_name);
        }
        free(cg->pending_functions);
    }
    free(cg->current_processing_function_name);

    if (cg->output_file) {
        fclose(cg->output_file);
    }

    free(cg);
}
