#include "codegen.h"
#include "parser.h"
#include "symbol_table.h"
#include <stdio.h>
#include <stdlib.h>

struct codegen_t *codegen_create_codegen(struct parser_t *restrict parser, const char *restrict out_filename) {
    struct codegen_t *cg = malloc(sizeof(struct codegen_t));
    if (!cg) {
        fprintf(stderr, "{ERR} Codegen memory allocation failed\n");
        return NULL;
    }

    cg->output_file = fopen(out_filename, "w");
    if (!cg->output_file) {
        fprintf(stderr, "{ERR} Could not open output file: %s\n", out_filename);
        free(cg);
        return NULL;
    }

    cg->parser = parser;
    cg->label_count = 0;
    cg->current_scope = parser->current_scope;
    cg->type_table = parser->type_table;

    fprintf(cg->output_file, "; --- Generated by Hupeyaszih Compiler ---\n");
    fprintf(cg->output_file, "section .text\n");
    fprintf(cg->output_file, "    global _start\n\n");

    return cg;
}

void codegen_generate(struct codegen_t *restrict codegen, struct parser_t *restrict parser, struct symbol_table *global_scope){
    codegen->current_scope = global_scope;
    codegen_calculate_offsets(global_scope, 0);

    for(int i = 0; i < parser->node_count; ++i){
        codegen_pre_codegen_analysis(parser->nodes[i], codegen->current_scope);
    }
    for(int i = 0; i < parser->node_count; ++i){
        codegen_visit_node(codegen, parser->nodes[i], global_scope);
    }
    fprintf(codegen->output_file, "_start:\n");

    fprintf(codegen->output_file, "    call main\n\n");
    fprintf(codegen->output_file, "    mov rdi, rax\n");
    fprintf(codegen->output_file, "    mov rax, 60\n");
    fprintf(codegen->output_file, "    syscall\n");
}

void codegen_pre_codegen_analysis(struct parser_node *node, struct symbol_table *current_scope) {
    if (!node) return;

    switch (node->type) {
        case PARSER_NODE_BLOCK: {
            int base = 0;
            if (current_scope) {

                base = current_scope->current_total_offset;
            }
            codegen_calculate_offsets(node->data.block.scope, base);

            for (int i = 0; i < node->data.block.count; i++) {
                struct parser_node *stmt = node->data.block.statements[i];
                if (stmt->type == PARSER_NODE_BLOCK || stmt->type == PARSER_NODE_FUNCTION) {
                    codegen_pre_codegen_analysis(stmt, node->data.block.scope);
                }
            }
            break;
        }
        case PARSER_NODE_FUNCTION: {
            codegen_pre_codegen_analysis(node->data.function.body, node->data.function.body->data.block.scope);
            break;
        }
        default: break;
    }
}

void codegen_visit_node(struct codegen_t *restrict codegen, struct parser_node *restrict node, struct symbol_table *global_scope) {
    if (!node) return;

    switch (node->type) {
        case PARSER_NODE_NUMBER:
            if(node->left_node) codegen_visit_node(codegen, node->left_node, global_scope);
            if(node->right_node) codegen_visit_node(codegen, node->right_node, global_scope);
            fprintf(codegen->output_file, "    mov rax, %s\n", node->data.literal_data);
            break;
        case PARSER_NODE_FUNCTION:
            fprintf(codegen->output_file, "%s:\n", node->data.function.name);

            fprintf(codegen->output_file, "    push rbp\n");
            fprintf(codegen->output_file, "    mov rbp, rsp\n");

            int stack_size = node->data.function.body->data.block.scope->total_stack_size;
            if (stack_size > 0) {
                fprintf(codegen->output_file, "    sub rsp, %d\n", stack_size);
            }

            const char *arg_regs[] = {"rdi", "rsi", "rdx", "rcx", "r8", "r9"};
            for (int i = 0; i < node->data.function.param_count; i++) {
                char *param_name = node->data.function.params->data.block.statements[i]->data.variable_name;
                struct symbol_t *sym = symbol_table_look_up(node->data.function.body->data.block.scope, param_name);

                if (sym) {
                    fprintf(codegen->output_file, "    mov [rbp-%d], %s\n", sym->stack_offset, arg_regs[i]);
                }
            }

            struct symbol_table *old_scope = codegen->current_scope;
            codegen->current_scope = node->data.function.body->data.block.scope;
            codegen_visit_node(codegen, node->data.function.body, global_scope);
            codegen->current_scope = old_scope;

            fprintf(codegen->output_file, "    leave\n");
            fprintf(codegen->output_file, "    ret\n");
    break;
        case PARSER_NODE_BLOCK: {
            struct symbol_table *previous = codegen->current_scope;
            codegen->current_scope = node->data.block.scope;

            for(int i = 0; i < node->data.block.count; ++i){
                codegen_visit_node(codegen, node->data.block.statements[i], global_scope);
            }
            codegen->current_scope = previous;
            break;
        }
        case PARSER_NODE_CALL: {
            const char *arg_regs[] = {"rdi", "rsi", "rdx", "rcx", "r8", "r9"};
            int arg_count = node->data.call.arg_count;

            for (int i = 0; i < arg_count; i++) {
                codegen_visit_node(codegen, node->data.call.args[i], global_scope);
                fprintf(codegen->output_file, "    push rax\n");
            }

            for (int i = arg_count - 1; i >= 0; i--) {
                fprintf(codegen->output_file, "    pop %s\n", arg_regs[i]);
            }

            fprintf(codegen->output_file, "    call %s\n", node->data.call.name);
            break;
        }
        case PARSER_NODE_VARIABLE_DECLARATION:
            if(node->right_node) codegen_visit_node(codegen, node->right_node, global_scope);
            fprintf(codegen->output_file, "    mov [rbp-%d], rax\n", symbol_table_look_up(codegen->current_scope, node->data.variable_name)->stack_offset);
            break;
        case PARSER_NODE_VARIABLE_ASSIGMENT:
            if(node->right_node) codegen_visit_node(codegen, node->right_node, global_scope);
            fprintf(codegen->output_file, "    mov [rbp-%d], rax\n", symbol_table_look_up(codegen->current_scope, node->data.variable_name)->stack_offset);
            break;
        case PARSER_NODE_IDENTIFIER:
            fprintf(codegen->output_file, "    mov rax, [rbp-%d]\n", symbol_table_look_up(codegen->current_scope, node->data.variable_name)->stack_offset);
            break;
        case PARSER_NODE_UNARY_MINUS:
            if(node->right_node) codegen_visit_node(codegen, node->right_node, global_scope);
            fprintf(codegen->output_file, "    neg rax\n");
            break;
        case PARSER_NODE_UNARY_BANG:
            if(node->right_node) codegen_visit_node(codegen, node->right_node, global_scope);
            fprintf(codegen->output_file, "    test rax, rax\n");
            fprintf(codegen->output_file, "    sete al\n");
            fprintf(codegen->output_file, "    movzx rax, al\n");
            break;
        case PARSER_NODE_BANG_EQUAL: 
            if(node->left_node) codegen_visit_node(codegen, node->left_node, global_scope);
            fprintf(codegen->output_file, "    push rax \n");
            if(node->right_node) codegen_visit_node(codegen, node->right_node, global_scope);
            fprintf(codegen->output_file, "    pop rcx \n");
            fprintf(codegen->output_file, "    cmp rcx, rax \n");
            fprintf(codegen->output_file, "    setne al \n");
            fprintf(codegen->output_file, "    movzx rax, al \n");
            break;
        case PARSER_NODE_EQUAL_EQUAL: 
            if(node->left_node) codegen_visit_node(codegen, node->left_node, global_scope);
            fprintf(codegen->output_file, "    push rax \n");
            if(node->right_node) codegen_visit_node(codegen, node->right_node, global_scope);
            fprintf(codegen->output_file, "    pop rcx \n");
            fprintf(codegen->output_file, "    cmp rcx, rax \n");
            fprintf(codegen->output_file, "    sete al \n");
            fprintf(codegen->output_file, "    movzx rax, al \n");
            break;
        case PARSER_NODE_LESS: 
            if(node->left_node) codegen_visit_node(codegen, node->left_node, global_scope);
            fprintf(codegen->output_file, "    push rax \n");
            if(node->right_node) codegen_visit_node(codegen, node->right_node, global_scope);
            fprintf(codegen->output_file, "    pop rcx \n");
            fprintf(codegen->output_file, "    cmp rcx, rax \n");
            fprintf(codegen->output_file, "    setl al \n");
            fprintf(codegen->output_file, "    movzx rax, al \n");
            break;
        case PARSER_NODE_GREATER: 
            if(node->left_node) codegen_visit_node(codegen, node->left_node, global_scope);
            fprintf(codegen->output_file, "    push rax \n");
            if(node->right_node) codegen_visit_node(codegen, node->right_node, global_scope);
            fprintf(codegen->output_file, "    pop rcx \n");
            fprintf(codegen->output_file, "    cmp rcx, rax \n");
            fprintf(codegen->output_file, "    setg al \n");
            fprintf(codegen->output_file, "    movzx rax, al \n");
            break;
        case PARSER_NODE_LESS_EQUAL: 
            if(node->left_node) codegen_visit_node(codegen, node->left_node, global_scope);
            fprintf(codegen->output_file, "    push rax \n");
            if(node->right_node) codegen_visit_node(codegen, node->right_node, global_scope);
            fprintf(codegen->output_file, "    pop rcx \n");
            fprintf(codegen->output_file, "    cmp rcx, rax \n");
            fprintf(codegen->output_file, "    setle al \n");
            fprintf(codegen->output_file, "    movzx rax, al \n");
            break;
        case PARSER_NODE_GREATER_EQUAL: 
            if(node->left_node) codegen_visit_node(codegen, node->left_node, global_scope);
            fprintf(codegen->output_file, "    push rax \n");
            if(node->right_node) codegen_visit_node(codegen, node->right_node, global_scope);
            fprintf(codegen->output_file, "    pop rcx \n");
            fprintf(codegen->output_file, "    cmp rcx, rax \n");
            fprintf(codegen->output_file, "    setge al \n");
            fprintf(codegen->output_file, "    movzx rax, al \n");
            break;
        case PARSER_NODE_PLUS: 
            if(node->left_node) codegen_visit_node(codegen, node->left_node, global_scope);
            fprintf(codegen->output_file, "    push rax \n");
            if(node->right_node) codegen_visit_node(codegen, node->right_node, global_scope);
            fprintf(codegen->output_file, "    pop rcx \n");
            fprintf(codegen->output_file, "    add rax, rcx \n");
            break;
        case PARSER_NODE_MINUS: 
            if(node->left_node) codegen_visit_node(codegen, node->left_node, global_scope);
            fprintf(codegen->output_file, "    push rax \n");
            if(node->right_node) codegen_visit_node(codegen, node->right_node, global_scope);
            fprintf(codegen->output_file, "    pop rcx \n");
            fprintf(codegen->output_file, "    sub rcx, rax \n");
            fprintf(codegen->output_file, "    mov rax, rcx \n");
            break;
        case PARSER_NODE_MUL: 
            if(node->left_node) codegen_visit_node(codegen, node->left_node, global_scope);
            fprintf(codegen->output_file, "    push rax \n");
            if(node->right_node) codegen_visit_node(codegen, node->right_node, global_scope);
            fprintf(codegen->output_file, "    pop rcx \n");
            fprintf(codegen->output_file, "    imul rcx, rax \n");
            fprintf(codegen->output_file, "    mov rax, rcx \n");
            break;
        case PARSER_NODE_DIVIDE: 
            if(node->left_node) codegen_visit_node(codegen, node->left_node, global_scope);
            fprintf(codegen->output_file, "    push rax \n");
            if(node->right_node) codegen_visit_node(codegen, node->right_node, global_scope);
            fprintf(codegen->output_file, "    mov rcx, rax\n");
            fprintf(codegen->output_file, "    pop rax\n");
            fprintf(codegen->output_file, "    cqo\n");
            fprintf(codegen->output_file, "    idiv rcx \n");
            break;
    }
}

void codegen_calculate_offsets(struct symbol_table *scope, int base_offset) {
    if (!scope) return;

    int current_offset = base_offset;

    for (int i = 0; i < scope->symbol_count; i++) {
        struct symbol_t *sym = &scope->symbols[i];
        if (sym->kind == SYMBOL_KIND_VARIABLE) {
            int size_padding = (sym->type->size + 7) & ~7;
            current_offset += size_padding;
            sym->stack_offset = current_offset; 
        }
    }
    
    scope->current_total_offset = current_offset;
    
    scope->total_stack_size = (current_offset + 15) & ~15;
    if (scope->parent && scope->total_stack_size > scope->parent->total_stack_size) {
        scope->parent->total_stack_size = scope->total_stack_size;
    }
}

void codegen_delete_codegen(struct codegen_t *restrict cg) {
    if (!cg) return;

    if (cg->output_file) {
        fclose(cg->output_file);
    }

    free(cg);
}
